# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'breakpoint', '<= 1.3'
#gem 'chunky_png', '1.3.4'
gem 'compass', '0.12.2'
#gem 'fssm', '0.2.10'
#gem 'multi_json', '1.11.1'
gem 'rake', '10.4.2'
#gem 'rb-fsevent', '0.9.5'
gem 'sass', '<= 3.2.19'
#gem 'sassy-maps', '0.4.0'
#gem 'zen-grids', '1.4'

